project_id = "psxkgfwizwpozfeygyza"

[functions.chat]
verify_jwt = true

[functions.generate-daily-wisdom]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.send-message-push]
verify_jwt = false
