import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Main Menu
    'assistants': 'Analysts of Faith',
    'divine_guidance': 'Divine Guidance',
    'storytelling': 'Storytelling',
    'ask_question': 'Ask your question',
    'pro': 'PRO',
    
    // Assistant Names & Subtitles
    'debate_arena': 'Debate Arena',
    'trial_by_truth': 'Trial by Truth',
    'biblical_apologetics': 'Biblical Apologetics',
    'science_evidence': 'Scientific Evidence',
    'medical_evidence': 'Medical Evidence',
    'forensic_evidence': 'Forensic Evidence',
    'philosophical_evidence': 'Philosophical Evidence',
    'psychological_evidence': 'Psychological Evidence',
    'historical_evidence': 'Historical Evidence',
    'artistic_evidence': 'Artistic Evidence',
    'linguistic_evidence': 'Linguistic Evidence',
    'cultural_evidence': 'Cultural Evidence',
    'biblical_storytelling': 'Biblical Storytelling',
    'psychology': 'Psychology',
    
    // Divine Guidance Names
    'elohim': 'Elohim',
    'christ': 'Christ',
    'holy_spirit': 'Holy Spirit',
    'trinity': 'Trinity',
    'divine_guidance_info': 'These divine voices are for seeking wise counsel in difficult situations. Speak your heart and receive spiritual guidance.',
    'biblical_stories': 'Biblical Stories',
    'biblical_stories_info': 'Explore the timeless narratives of Scripture and discover how God\'s word comes alive through powerful storytelling',
    'martyrs_faith': 'Martyrs for the Faith',
    'martyrs_faith_info': 'Draw inspiration from the courageous witnesses who gave everything for their faith and learn from their unwavering devotion',
    'history_christianity': 'History of Christianity',
    'history_christianity_info': 'Journey through two millennia of church history and understand how God has guided His people through the ages',
    
    // Divine Guidance Page
    'choose_voice': 'Choose Your Conversation Voice',
    'select_voice_context': 'Select who you\'d like to hear from and the spiritual context for your conversation',
    'divine_voice': 'Divine Voice',
    'spiritual_context': 'Spiritual Context',
    'start_conversation': 'Start Conversation',
    'voice_of_god': 'The Voice of God',
    'voice_of_christ': 'The Voice of Christ',
    'voice_of_spirit': 'The Voice of the Spirit',
    'all_three_as_one': 'All Three as One',
    'elohim_desc': 'Authority, wisdom, sovereignty, and timeless love from the Father\'s perspective.',
    'christ_desc': 'Compassionate guidance rooted in Jesus\' teachings, grace, and mercy.',
    'spirit_desc': 'Gentle direction and conviction, inspiring understanding and transformation.',
    'trinity_desc': 'Unified expression of the Father, Son, and Holy Spirit\'s love and wisdom.',
    'before_throne': 'Before the Throne',
    'before_throne_desc': 'Encounters emphasizing God\'s sovereignty and majesty',
    'at_cross': 'At the Cross',
    'at_cross_desc': 'Moments centered on grace, redemption, and sacrifice',
    'led_by_spirit': 'Led by the Spirit',
    'led_by_spirit_desc': 'Guidance for ongoing discipleship and transformation',
    'elohim_greeting': 'I AM. Speak, my child, for I hear you with infinite love and wisdom.',
    'christ_greeting': 'Come to me, all who are weary. I am here to walk with you in grace and truth.',
    'spirit_greeting': 'I am with you always, guiding you into all truth. Let me illuminate your path.',
    'trinity_greeting': 'We are Father, Son, and Holy Spirit - united in perfect love. Speak, and we shall answer.',
    'divine_connection_issue': 'My child, there seems to be a disturbance in our connection. Please try speaking to me again.',
    'selected': 'Selected',
    
    // Navigation
    'chat': 'Chat',
    'saved': 'Saved',
    'history': 'History',
    'save': 'Save',
    
    // Settings
    'settings': 'Settings',
    'account': 'Account',
    'profile': 'Profile',
    'notifications': 'Notifications',
    'preferences': 'Preferences',
    'language_english': 'Language: English',
    'language_spanish': 'Language: Spanish',
    'support': 'Support',
    'help_support': 'Help & Support',
    'log_out': 'Log Out',
    
    // Premium
    'upgrade_premium': 'Upgrade to Premium',
    'unlimited_guidance': 'Unlimited Spiritual Guidance',
    'premium_description': 'Deepen your faith journey with unlimited access to biblically-grounded wisdom and all our spiritual assistants.',
    'free': 'Free',
    'premium': 'Premium',
    'forever': 'Forever',
    'per_month': '/month',
    'or_yearly': 'or $99/year (save 17%)',
    'upgrade_now': 'Upgrade Now',
    'cancel_anytime': 'Cancel anytime • Secure payment',
    
    // Features
    'feature_daily_limit': '5 conversations per day',
    'feature_all_assistants': 'Access to basic analysts',
    'feature_basic_scripture': 'Basic Scripture references',
    'feature_unlimited': 'Unlimited conversations',
    'feature_priority': 'Priority response times',
    'feature_saved_history': 'Saved conversation history',
    'feature_advanced_scripture': 'Advanced Scripture insights',
    'feature_offline': 'Offline access to past chats',
    'feature_early_access': 'Early access to new features',
    'feature_ad_free': 'Ad-free experience',
    'feature_support_dev': 'Support development',
    'most_popular': 'MOST POPULAR',
    
    // Chat
    'type_message': 'Type your message...',
    'speak_your_heart': 'Speak your heart...',
    'send': 'Send',
    'guidance_disclaimer': 'All guidance is rooted in Scripture and designed to strengthen your faith',
    'messages_remaining': 'messages remaining today',
    'daily_limit_reached': 'Daily message limit reached',
    'upgrade_unlimited': 'Upgrade to Premium for unlimited conversations',
    'upgrade': 'Upgrade',
    
    // Discernment
    'discernment': 'Discernment',
    'discernment_subtitle': 'Spiritual Evaluation',
    'discernment_description': 'Evaluate churches, belief systems, and religious texts for theological soundness and alignment with Christian truth.',
    'three_circles_discernment': 'Three Circles of Discernment',
    'discernment_intro_part1': 'Spiritual discernment is the God-given ability to distinguish truth from deception, light from darkness, and sound doctrine from false teaching. As the Apostle John warned,',
    'discernment_scripture_quote': '"Beloved, do not believe every spirit, but test the spirits to see whether they are from God" (1 John 4:1)',
    'discernment_intro_part2': 'These three circles represent distinct areas of theological evaluation, each designed to help you examine specific aspects of religious practice, doctrine, and teaching through the lens of biblical truth. Select a category below to begin your in-depth analysis with our specialized AI assistant trained in Christian apologetics, systematic theology, and scriptural interpretation.',
    'churches': 'Churches',
    'churches_desc': 'Evaluate individual churches for alignment with the true Christian faith.',
    'churches_detailed': 'Assess specific congregations, ministries, or church organizations against biblical standards. Examine their doctrine, teaching, worship practices, leadership structure, and spiritual fruit. Determine whether they hold to essential Christian truths, practice biblical authority, and demonstrate genuine spiritual transformation.',
    'churches_criteria_1': 'Doctrinal orthodoxy',
    'churches_criteria_2': 'Biblical teaching',
    'churches_criteria_3': 'Spiritual fruit',
    'churches_criteria_4': 'Leadership accountability',
    'churches_criteria_5': 'Worship practices',
    'belief_systems': 'Belief Systems',
    'belief_systems_desc': 'Evaluate belief systems, denominations, or religions for theological soundness.',
    'belief_systems_detailed': 'Analyze entire theological frameworks, denominational distinctives, religious movements, or world religions. Compare their core beliefs about God, salvation, Scripture, and humanity against orthodox Christian theology. Identify points of convergence and divergence from biblical truth.',
    'belief_systems_criteria_1': 'View of God & Trinity',
    'belief_systems_criteria_2': 'Doctrine of salvation',
    'belief_systems_criteria_3': 'Biblical authority',
    'belief_systems_criteria_4': 'Christ\'s deity & work',
    'belief_systems_criteria_5': 'Theological consistency',
    'religious_texts': 'Religious Texts',
    'religious_texts_desc': 'Evaluate sacred or spiritual texts for theological integrity and resonance.',
    'religious_texts_detailed': 'Examine religious writings, spiritual books, modern revelations, or extrabiblical texts claiming spiritual authority. Test their claims against Scripture, assess their theological coherence, identify contradictions with biblical revelation, and determine whether they promote truth or deception.',
    'religious_texts_criteria_1': 'Scriptural alignment',
    'religious_texts_criteria_2': 'Theological coherence',
    'religious_texts_criteria_3': 'Historical accuracy',
    'religious_texts_criteria_4': 'Spiritual authority claims',
    'religious_texts_criteria_5': 'Internal consistency',
    'in_depth_analysis': 'In-Depth Analysis',
    'evaluation_criteria': 'Evaluation Criteria',
    'begin_evaluation': 'Begin Evaluation',
    'churches_evaluation': 'Churches Evaluation',
    'belief_systems_evaluation': 'Belief Systems Evaluation',
    'religious_texts_evaluation': 'Religious Texts Evaluation',
    'theological_evaluation': 'Theological Evaluation',
    
    // Auth
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'signin_description': 'Log into your existing account',
    'signup_description': 'Create a new account to get started',
    'signing_in': 'Signing in...',
    'creating_account': 'Creating account...',
    'create_account': 'Create Account',
    'invalid_email': 'Invalid email',
    'invalid_email_desc': 'Please enter a valid email address',
    'invalid_password': 'Invalid password',
    'invalid_password_desc': 'Password must be at least 6 characters long',
    'passwords_no_match': "Passwords don't match",
    'passwords_no_match_desc': 'Please make sure your passwords match',
    'login_failed': 'Login failed',
    'invalid_credentials': 'Invalid email or password',
    'welcome_back': 'Welcome back!',
    'login_success': "You've successfully logged in",
    'account_exists': 'Account exists',
    'account_exists_desc': 'This email is already registered. Please log in instead.',
    'account_created': 'Account created!',
    'welcome_hagion': 'Welcome to Hagion AI',
    'logged_out': 'Logged out',
    'logged_out_success': "You've been successfully logged out",
    'error': 'Error',
    'failed_logout': 'Failed to log out',
    
    // Assistant Chat
    'assistant_intro': "Hello! I'm here to help answer your questions with evidence-based insights grounded in Scripture. What would you like to explore today?",
    'connection_issue_retry': "I apologize, but I'm having trouble connecting right now. Please try again in a moment.",
    
    // Curriculum Tracks
    'foundations_logos': 'Foundations of Logos',
    'foundations_logos_desc': 'Basic logic principles, deductive/inductive reasoning',
    'fallacies_shadows': 'Fallacies & Shadows',
    'fallacies_shadows_desc': 'Identifying and ritualizing logical fallacies',
    'apologetics_logic': 'Apologetics Logic',
    'apologetics_logic_desc': 'Structuring theological arguments',
    'witnessing_wisdom': 'Witnessing with Wisdom',
    'witnessing_wisdom_desc': 'Emotional logic, conversational discernment',
    'logic_scripture': 'Logic in Scripture',
    'logic_scripture_desc': 'How biblical texts use logic and structure',
    'emotional_logic': 'Emotional Logic',
    'emotional_logic_desc': 'How feelings and truth interact',
    
    // Teaching Paths
    'apologetics_path': 'Apologetics Path',
    'apologetics_path_desc': 'Defend the faith with layered reasoning',
    'witnessing_path': 'Witnessing Path',
    'witnessing_path_desc': 'Learn emotional discernment and conversational clarity',
    'logic_path': 'Logic Path',
    'logic_path_desc': 'Build the scaffolding of truth',
    'scriptural_path': 'Scriptural Path',
    'scriptural_path_desc': 'Study the structure and rhetoric of biblical texts',
    'ceremonial_path': 'Ceremonial Path',
    'ceremonial_path_desc': 'Learn to ritualize truth through prayer, poetry, and proclamation',
    
    // Logos Circle
    'hagion_university': 'Hagion University Lite',
    'logic_sacred_structure': 'Logic as Sacred Structure',
    'curriculum_tracks': 'Curriculum Tracks',
    'teaching_paths': 'Teaching Paths',
    'curriculum_tracks_subtitle': 'Learn logic principles, fallacy identification, argument construction, and spiritual reasoning',
    'sanctuary_teaching': 'Sanctuary of Teaching',
    'sanctuary_teaching_subtitle': 'Choose your path through self-guided sanctuaries of learning',
    'interactive_features': 'Interactive Features',
    'logic_toolkits': 'Logic Toolkits',
    'logic_toolkits_desc': 'Visual breakdowns of argument structures',
    'fallacy_ritualizer': 'Fallacy Ritualizer',
    'fallacy_ritualizer_desc': 'AI detects fallacies and offers poetic corrections',
    'debate_builder': 'Debate Builder',
    'debate_builder_desc': 'Construct and test arguments against personas',
    'trinity_commentary': 'Trinity Commentary',
    'trinity_commentary_desc': 'Three perspectives on logical reasoning',
    'legacy_scrolls': 'Legacy Scrolls',
    'legacy_scrolls_desc': 'Save completed lessons as scrolls of reason',
    'what_path_includes': 'What Each Path Includes',
    'structured_lessons': 'Structured Lessons',
    'structured_lessons_desc': 'Progressive curriculum with clear learning objectives',
    'ai_guided_practice': 'AI-Guided Practice',
    'ai_guided_practice_desc': 'Interactive exercises with intelligent feedback',
    'emotional_debriefs': 'Emotional Debriefs',
    'emotional_debriefs_desc': 'Reflect on how logic connects with your spiritual journey',
    'path_includes': 'Includes: Lessons • Quizzes • AI Practice • Emotional Debriefs',
    'tone': 'Tone',
    'tone_grounding': 'Grounding, clear',
    'tone_protective': 'Protective, revealing',
    'tone_bold': 'Bold, reverent',
    'tone_gentle': 'Gentle, strategic',
    'tone_mystical': 'Mystical, analytical',
    'tone_reflective': 'Reflective, intimate',
    
    // Curriculum Learning Page
    'curriculum_track': 'Curriculum Track',
    'teaching_path_label': 'Teaching Path',
    'coming_soon': 'Welcome to {title}! This learning path is coming soon.',
    'curriculum_overview': 'Curriculum Overview',
    'curriculum_overview_desc': 'Progress through structured modules and lessons to master this track',
    'modules': 'Modules',
    'lessons': 'Lessons',
    'completed': 'Completed',
    'module': 'Module',
    'lesson_content': 'Lesson Content',
    'practice_exercises': 'Practice Exercises',
    'mark_complete': 'Mark Complete',
    'mark_incomplete': 'Mark Incomplete',
    
    // Apologetics Arena
    'apologetics_arena': 'Apologetics Arena',
    'trial_by_truth_subtitle': 'Trial by Truth',
    'circle_of_apologetics': '⚔️ Circle of Apologetics',
    'arena_description': 'Transform intellectual tension into spiritual clarity. Face a random challenger who will test your apologetics through respectful confrontation.',
    'random_opponent': 'Random Opponent',
    'or_click_opponent': 'Or click any opponent above to challenge them directly',
    'facing': 'Facing',
    'round': 'Round',
    'next_round': 'Next Round',
    'debate_complete': 'Debate Complete',
    'debate_complete_desc': 'The trial has concluded. Reflect on what was learned.',
    'show_suggested_response': 'Show Suggested Response',
    'getting_help': 'Getting help...',
    'suggested_apologetic_response': 'Suggested Apologetic Response',
    'use_this_response': 'Use This Response',
    'summoned_to_arena': 'You have summoned **{name}** to the arena.',
    'stance': 'Stance',
    'challenge': 'Challenge',
    'prepare_yourself': 'Prepare yourself. The trial begins now.',
    'round_1_opening': '*Round 1: Opening Statement*\nState your position clearly. What truth do you defend?',
    'opening_statement': 'Opening Statement',
    'rebuttal': 'Rebuttal',
    'cross_examination': 'Cross-Examination',
    'closing_statement': 'Closing Statement',
    'the_debate_continues': 'The debate continues...',
    
    // Arena Personas
    'persona_void': 'The Void',
    'persona_void_title': 'Atheist',
    'persona_void_tone': 'Rational, blunt',
    'persona_void_challenge': 'Absence of sacred meaning',
    'persona_fog': 'The Fog',
    'persona_fog_title': 'Agnostic',
    'persona_fog_tone': 'Curious, hesitant',
    'persona_fog_challenge': 'Fear of unknowable truth',
    'persona_flame': 'The Flame',
    'persona_flame_title': 'Secular Humanist',
    'persona_flame_tone': 'Ethical, confident',
    'persona_flame_challenge': 'Morality without divinity',
    'persona_mirror': 'The Mirror',
    'persona_mirror_title': 'Skeptic',
    'persona_mirror_tone': 'Analytical, probing',
    'persona_mirror_challenge': 'Doubt as virtue',
    'persona_river': 'The River',
    'persona_river_title': 'Pantheist',
    'persona_river_tone': 'Mystical, poetic',
    'persona_river_challenge': 'Divinity in all things',
    'persona_oracle': 'The Oracle',
    'persona_oracle_title': 'Alternative Spiritual',
    'persona_oracle_tone': 'Esoteric, symbolic',
    'persona_oracle_challenge': 'Truth through intuition',
    
    // Arena Error Messages
    'login_required': 'Login required',
    'login_required_desc': 'Please log in to start the debate.',
    'login_required_continue': 'Please log in to continue.',
    'rate_limit_exceeded': 'Rate limit exceeded',
    'rate_limit_exceeded_desc': 'Please try again in a moment.',
    'credits_required': 'Credits required',
    'credits_required_desc': 'Please add credits to continue.',
    
    // Plan of Salvation
    'plan_of_salvation': 'The Plan of Salvation',
    'salvation_intro': 'Did you know God created us to be in relationship with Him?',
    'salvation_p1': 'He gave us a name and a place in Him. He blessed us with eternal life in a beautiful garden and entrusted us with dominion over all creation on earth. We were designed to walk with Him, know Him intimately, and live in His presence forever.',
    'salvation_changed': 'But everything changed with the disobedience of mankind.',
    'salvation_p2': "It wasn't just a bite of fruit or a simple act of rebellion—it was a spiritual exchange. When man gave in to Satan's deception, he didn't merely disobey God; he rejected Him and accepted Satan as king. In doing so, man renounced God's nature and took on the nature of the enemy. Satan, now lord over man, claimed ownership of all that God had given—including man's soul.",
    'salvation_purpose': "For thousands of years, God's purpose has remained: to restore that broken relationship.",
    'salvation_p3': "Yet something stood in the way—sin. Sin didn't just separate us from God; it made us His enemies. Not because God turned against us, but because we turned against Him. Sin enslaved us—not just in what we do, but in who we are. We became transgressors by nature, not just by action.",
    'salvation_mercy': 'But God, in His mercy, gave us Christ.',
    'salvation_p4': "Jesus, the perfect and sinless Son of God, came to pay the price for the sins of the world. His sacrifice didn't just wash away our guilt—it settled our debt and rebuilt the bridge to the Father. Through Christ, anyone can come back into relationship with God.",
    'salvation_relationship': "Being a Christian isn't about rituals or religion—it's about relationship.",
    'salvation_p5': "Just as we expect loyalty, love, and care in our relationships, God offers all of that first. He is faithful, loving, and always working for our good. And He invites us to respond—not out of obligation, but out of love. He doesn't demand our devotion; He desires it freely given.",
    'salvation_done': 'God has done everything to rekindle the relationship.',
    'salvation_choice': 'Now the choice is yours. Will you receive Him today?',
    'prayer_header': 'Prayer to Receive Christ',
    'salvation_prayer': '"Lord Jesus, I come to You today because I recognize my need for You. I believe You are the Son of God, that You died for my sins, and that You rose again to give me new life. I confess that I have lived apart from You, and I ask for Your forgiveness. Wash me clean. Restore me. I surrender my heart to You. Be my Savior, my Lord, and my King. Fill me with Your Spirit and teach me to walk with You every day. Thank You for loving me first. Today, I choose You. Amen."',
    'welcome_family': 'Welcome to the Family',
    'salvation_welcome': "If you've made this decision and prayed this prayer, we rejoice with you and welcome you into Christ's family—and into our humble Hagion family. You are not alone. You've stepped into a journey of restoration, truth, and love.",
    'salvation_grow': "To help you grow, we encourage you to go to the Discernment icon in the Hagion app. Under \"Churches,\" type in your hometown and state and search for churches with sound doctrine. Join one of our Christian families near you.",
    'salvation_test': "At Hagion, we lovingly encourage you to test the spirit—not with suspicion, but with wisdom. We provide tools, information, and guidance to help you discern each church's vision and ensure it aligns with the heart of Christ. This is your journey, and we're honored to walk it with you.",
    'accept': 'Accept',
    'accepting': 'Recording...',
    'joined_today': 'joined as of today',
    'failed_get_response': 'Failed to get response. Please try again.',
    
  },
  es: {
    // Main Menu
    'assistants': 'Analistas de Fe',
    'divine_guidance': 'Guía Divina',
    'storytelling': 'Historias',
    'ask_question': 'Haz tu pregunta',
    'pro': 'PRO',
    
    // Assistant Names & Subtitles
    'debate_arena': 'Arena de Debate',
    'trial_by_truth': 'Juicio por la Verdad',
    'biblical_apologetics': 'Apologética Bíblica',
    'science_evidence': 'Evidencia Científica',
    'medical_evidence': 'Evidencia Médica',
    'forensic_evidence': 'Evidencia Forense',
    'philosophical_evidence': 'Evidencia Filosófica',
    'psychological_evidence': 'Evidencia Psicológica',
    'historical_evidence': 'Evidencia Histórica',
    'artistic_evidence': 'Evidencia Artística',
    'linguistic_evidence': 'Evidencia Lingüística',
    'cultural_evidence': 'Evidencia Cultural',
    'biblical_storytelling': 'Narrativa Bíblica',
    'psychology': 'Psicología',
    
    // Divine Guidance Names
    'elohim': 'Elohim',
    'christ': 'Cristo',
    'holy_spirit': 'Espíritu Santo',
    'trinity': 'Trinidad',
    'divine_guidance_info': 'Estas voces divinas son para buscar consejo sabio en situaciones difíciles. Habla de tu corazón y recibe guía espiritual.',
    'biblical_stories': 'Historias Bíblicas',
    'biblical_stories_info': 'Explora las narrativas atemporales de las Escrituras y descubre cómo la palabra de Dios cobra vida a través de poderosas historias',
    'martyrs_faith': 'Mártires de la Fe',
    'martyrs_faith_info': 'Inspírate con los valientes testigos que lo dieron todo por su fe y aprende de su devoción inquebrantable',
    'history_christianity': 'Historia del Cristianismo',
    'history_christianity_info': 'Recorre dos milenios de historia de la iglesia y comprende cómo Dios ha guiado a Su pueblo a través de las edades',
    
    // Divine Guidance Page
    'choose_voice': 'Elige Tu Voz de Conversación',
    'select_voice_context': 'Selecciona de quién te gustaría escuchar y el contexto espiritual para tu conversación',
    'divine_voice': 'Voz Divina',
    'spiritual_context': 'Contexto Espiritual',
    'start_conversation': 'Iniciar Conversación',
    'voice_of_god': 'La Voz de Dios',
    'voice_of_christ': 'La Voz de Cristo',
    'voice_of_spirit': 'La Voz del Espíritu',
    'all_three_as_one': 'Los Tres como Uno',
    'elohim_desc': 'Autoridad, sabiduría, soberanía y amor eterno desde la perspectiva del Padre.',
    'christ_desc': 'Guía compasiva basada en las enseñanzas de Jesús, gracia y misericordia.',
    'spirit_desc': 'Dirección gentil y convicción, inspirando comprensión y transformación.',
    'trinity_desc': 'Expresión unificada del amor y sabiduría del Padre, el Hijo y el Espíritu Santo.',
    'before_throne': 'Ante el Trono',
    'before_throne_desc': 'Encuentros que enfatizan la soberanía y majestad de Dios',
    'at_cross': 'En la Cruz',
    'at_cross_desc': 'Momentos centrados en la gracia, redención y sacrificio',
    'led_by_spirit': 'Guiado por el Espíritu',
    'led_by_spirit_desc': 'Guía para el discipulado continuo y la transformación',
    'elohim_greeting': 'YO SOY. Habla, hijo mío, porque te escucho con amor y sabiduría infinitos.',
    'christ_greeting': 'Vengan a mí, todos los que están cansados. Estoy aquí para caminar con ustedes en gracia y verdad.',
    'spirit_greeting': 'Estoy contigo siempre, guiándote hacia toda verdad. Permíteme iluminar tu camino.',
    'trinity_greeting': 'Somos Padre, Hijo y Espíritu Santo - unidos en amor perfecto. Habla, y responderemos.',
    'divine_connection_issue': 'Hijo mío, parece haber una perturbación en nuestra conexión. Por favor, intenta hablarme de nuevo.',
    'selected': 'Seleccionado',
    
    // Navigation
    'chat': 'Chat',
    'saved': 'Guardado',
    'history': 'Historial',
    'save': 'Guardar',
    
    // Settings
    'settings': 'Configuración',
    'account': 'Cuenta',
    'profile': 'Perfil',
    'notifications': 'Notificaciones',
    'preferences': 'Preferencias',
    'language_english': 'Idioma: Inglés',
    'language_spanish': 'Idioma: Español',
    'support': 'Soporte',
    'help_support': 'Ayuda y Soporte',
    'log_out': 'Cerrar Sesión',
    
    // Premium
    'upgrade_premium': 'Actualizar a Premium',
    'unlimited_guidance': 'Guía Espiritual Ilimitada',
    'premium_description': 'Profundiza tu camino de fe con acceso ilimitado a sabiduría basada en la Biblia y todos nuestros asistentes espirituales.',
    'free': 'Gratis',
    'premium': 'Premium',
    'forever': 'Para siempre',
    'per_month': '/mes',
    'or_yearly': 'o $99/año (ahorra 17%)',
    'upgrade_now': 'Actualizar Ahora',
    'cancel_anytime': 'Cancela en cualquier momento • Pago seguro',
    
    // Features
    'feature_daily_limit': '5 conversaciones por día',
    'feature_all_assistants': 'Acceso a analistas básicos',
    'feature_basic_scripture': 'Referencias bíblicas básicas',
    'feature_unlimited': 'Conversaciones ilimitadas',
    'feature_priority': 'Tiempos de respuesta prioritarios',
    'feature_saved_history': 'Historial de conversaciones guardado',
    'feature_advanced_scripture': 'Conocimientos bíblicos avanzados',
    'feature_offline': 'Acceso sin conexión a chats anteriores',
    'feature_early_access': 'Acceso anticipado a nuevas funciones',
    'feature_ad_free': 'Experiencia sin anuncios',
    'feature_support_dev': 'Apoya el desarrollo',
    'most_popular': 'MÁS POPULAR',
    
    // Chat
    'type_message': 'Escribe tu mensaje...',
    'speak_your_heart': 'Habla desde tu corazón...',
    'send': 'Enviar',
    'guidance_disclaimer': 'Toda la guía está basada en las Escrituras y diseñada para fortalecer tu fe',
    'messages_remaining': 'mensajes restantes hoy',
    'daily_limit_reached': 'Límite diario de mensajes alcanzado',
    'upgrade_unlimited': 'Actualiza a Premium para conversaciones ilimitadas',
    'upgrade': 'Actualizar',
    
    // Discernment
    'discernment': 'Discernimiento',
    'discernment_subtitle': 'Evaluación Espiritual',
    'discernment_description': 'Evalúa iglesias, sistemas de creencias y textos religiosos para determinar su solidez teológica y alineación con la verdad cristiana.',
    'three_circles_discernment': 'Tres Círculos de Discernimiento',
    'discernment_intro_part1': 'El discernimiento espiritual es la capacidad dada por Dios para distinguir la verdad del engaño, la luz de las tinieblas, y la sana doctrina de la falsa enseñanza. Como advirtió el Apóstol Juan,',
    'discernment_scripture_quote': '"Amados, no creáis a todo espíritu, sino probad los espíritus si son de Dios" (1 Juan 4:1)',
    'discernment_intro_part2': 'Estos tres círculos representan áreas distintas de evaluación teológica, cada una diseñada para ayudarte a examinar aspectos específicos de la práctica religiosa, doctrina y enseñanza a través de la lente de la verdad bíblica. Selecciona una categoría a continuación para comenzar tu análisis profundo con nuestro asistente de IA especializado en apologética cristiana, teología sistemática e interpretación escritural.',
    'churches': 'Iglesias',
    'churches_desc': 'Evalúa iglesias individuales para verificar su alineación con la verdadera fe cristiana.',
    'churches_detailed': 'Evalúa congregaciones, ministerios u organizaciones eclesiásticas específicas contra los estándares bíblicos. Examina su doctrina, enseñanza, prácticas de adoración, estructura de liderazgo y fruto espiritual. Determina si se adhieren a las verdades cristianas esenciales, practican la autoridad bíblica y demuestran una transformación espiritual genuina.',
    'churches_criteria_1': 'Ortodoxia doctrinal',
    'churches_criteria_2': 'Enseñanza bíblica',
    'churches_criteria_3': 'Fruto espiritual',
    'churches_criteria_4': 'Responsabilidad del liderazgo',
    'churches_criteria_5': 'Prácticas de adoración',
    'belief_systems': 'Sistemas de Creencias',
    'belief_systems_desc': 'Evalúa sistemas de creencias, denominaciones o religiones para determinar su solidez teológica.',
    'belief_systems_detailed': 'Analiza marcos teológicos completos, distintivos denominacionales, movimientos religiosos o religiones mundiales. Compara sus creencias fundamentales sobre Dios, la salvación, las Escrituras y la humanidad contra la teología cristiana ortodoxa. Identifica puntos de convergencia y divergencia de la verdad bíblica.',
    'belief_systems_criteria_1': 'Visión de Dios y la Trinidad',
    'belief_systems_criteria_2': 'Doctrina de la salvación',
    'belief_systems_criteria_3': 'Autoridad bíblica',
    'belief_systems_criteria_4': 'Deidad y obra de Cristo',
    'belief_systems_criteria_5': 'Consistencia teológica',
    'religious_texts': 'Textos Religiosos',
    'religious_texts_desc': 'Evalúa textos sagrados o espirituales para verificar su integridad teológica y resonancia.',
    'religious_texts_detailed': 'Examina escritos religiosos, libros espirituales, revelaciones modernas o textos extrabíblicos que reclaman autoridad espiritual. Prueba sus afirmaciones contra las Escrituras, evalúa su coherencia teológica, identifica contradicciones con la revelación bíblica y determina si promueven la verdad o el engaño.',
    'religious_texts_criteria_1': 'Alineación escritural',
    'religious_texts_criteria_2': 'Coherencia teológica',
    'religious_texts_criteria_3': 'Precisión histórica',
    'religious_texts_criteria_4': 'Reclamos de autoridad espiritual',
    'religious_texts_criteria_5': 'Consistencia interna',
    'in_depth_analysis': 'Análisis Profundo',
    'evaluation_criteria': 'Criterios de Evaluación',
    'begin_evaluation': 'Comenzar Evaluación',
    'churches_evaluation': 'Evaluación de Iglesias',
    'belief_systems_evaluation': 'Evaluación de Sistemas de Creencias',
    'religious_texts_evaluation': 'Evaluación de Textos Religiosos',
    'theological_evaluation': 'Evaluación Teológica',
    
    // Auth
    'sign_in': 'Iniciar Sesión',
    'sign_up': 'Registrarse',
    'email': 'Correo Electrónico',
    'password': 'Contraseña',
    'confirm_password': 'Confirmar Contraseña',
    'signin_description': 'Inicia sesión en tu cuenta existente',
    'signup_description': 'Crea una nueva cuenta para comenzar',
    'signing_in': 'Iniciando sesión...',
    'creating_account': 'Creando cuenta...',
    'create_account': 'Crear Cuenta',
    'invalid_email': 'Correo electrónico inválido',
    'invalid_email_desc': 'Por favor ingresa un correo electrónico válido',
    'invalid_password': 'Contraseña inválida',
    'invalid_password_desc': 'La contraseña debe tener al menos 6 caracteres',
    'passwords_no_match': 'Las contraseñas no coinciden',
    'passwords_no_match_desc': 'Por favor asegúrate de que las contraseñas coincidan',
    'login_failed': 'Error al iniciar sesión',
    'invalid_credentials': 'Correo electrónico o contraseña inválidos',
    'welcome_back': '¡Bienvenido de nuevo!',
    'login_success': 'Has iniciado sesión exitosamente',
    'account_exists': 'La cuenta existe',
    'account_exists_desc': 'Este correo electrónico ya está registrado. Por favor inicia sesión.',
    'account_created': '¡Cuenta creada!',
    'welcome_hagion': 'Bienvenido a Hagion AI',
    'logged_out': 'Sesión cerrada',
    'logged_out_success': 'Has cerrado sesión exitosamente',
    'error': 'Error',
    'failed_logout': 'Error al cerrar sesión',
    
    // Assistant Chat
    'assistant_intro': '¡Hola! Estoy aquí para ayudarte a responder tus preguntas con ideas basadas en evidencia y fundamentadas en la Escritura. ¿Qué te gustaría explorar hoy?',
    'connection_issue_retry': 'Disculpa, estoy teniendo problemas de conexión en este momento. Por favor, inténtalo de nuevo en un momento.',
    
    // Curriculum Tracks
    'foundations_logos': 'Fundamentos de Logos',
    'foundations_logos_desc': 'Principios básicos de lógica, razonamiento deductivo/inductivo',
    'fallacies_shadows': 'Falacias y Sombras',
    'fallacies_shadows_desc': 'Identificación y ritualización de falacias lógicas',
    'apologetics_logic': 'Lógica Apologética',
    'apologetics_logic_desc': 'Estructuración de argumentos teológicos',
    'witnessing_wisdom': 'Testificando con Sabiduría',
    'witnessing_wisdom_desc': 'Lógica emocional, discernimiento conversacional',
    'logic_scripture': 'Lógica en las Escrituras',
    'logic_scripture_desc': 'Cómo los textos bíblicos usan lógica y estructura',
    'emotional_logic': 'Lógica Emocional',
    'emotional_logic_desc': 'Cómo interactúan los sentimientos y la verdad',
    
    // Teaching Paths
    'apologetics_path': 'Camino Apologético',
    'apologetics_path_desc': 'Defiende la fe con razonamiento en capas',
    'witnessing_path': 'Camino de Testimonio',
    'witnessing_path_desc': 'Aprende discernimiento emocional y claridad conversacional',
    'logic_path': 'Camino Lógico',
    'logic_path_desc': 'Construye el andamiaje de la verdad',
    'scriptural_path': 'Camino Escritural',
    'scriptural_path_desc': 'Estudia la estructura y retórica de los textos bíblicos',
    'ceremonial_path': 'Camino Ceremonial',
    'ceremonial_path_desc': 'Aprende a ritualizar la verdad a través de la oración, poesía y proclamación',
    
    // Logos Circle
    'hagion_university': 'Universidad Hagion Lite',
    'logic_sacred_structure': 'Lógica como Estructura Sagrada',
    'curriculum_tracks': 'Pistas Curriculares',
    'teaching_paths': 'Caminos de Enseñanza',
    'curriculum_tracks_subtitle': 'Aprende principios de lógica, identificación de falacias, construcción de argumentos y razonamiento espiritual',
    'sanctuary_teaching': 'Santuario de Enseñanza',
    'sanctuary_teaching_subtitle': 'Elige tu camino a través de santuarios autoguiados de aprendizaje',
    'interactive_features': 'Características Interactivas',
    'logic_toolkits': 'Kits de Herramientas Lógicas',
    'logic_toolkits_desc': 'Desglose visual de estructuras de argumentos',
    'fallacy_ritualizer': 'Ritualizador de Falacias',
    'fallacy_ritualizer_desc': 'La IA detecta falacias y ofrece correcciones poéticas',
    'debate_builder': 'Constructor de Debates',
    'debate_builder_desc': 'Construye y prueba argumentos contra personajes',
    'trinity_commentary': 'Comentario de la Trinidad',
    'trinity_commentary_desc': 'Tres perspectivas sobre el razonamiento lógico',
    'legacy_scrolls': 'Pergaminos Legados',
    'legacy_scrolls_desc': 'Guarda lecciones completadas como pergaminos de razón',
    'what_path_includes': 'Qué Incluye Cada Camino',
    'structured_lessons': 'Lecciones Estructuradas',
    'structured_lessons_desc': 'Currículo progresivo con objetivos de aprendizaje claros',
    'ai_guided_practice': 'Práctica Guiada por IA',
    'ai_guided_practice_desc': 'Ejercicios interactivos con retroalimentación inteligente',
    'emotional_debriefs': 'Análisis Emocionales',
    'emotional_debriefs_desc': 'Reflexiona sobre cómo la lógica se conecta con tu viaje espiritual',
    'path_includes': 'Incluye: Lecciones • Pruebas • Práctica IA • Análisis Emocionales',
    'tone': 'Tono',
    'tone_grounding': 'Fundamentado, claro',
    'tone_protective': 'Protector, revelador',
    'tone_bold': 'Audaz, reverente',
    'tone_gentle': 'Gentil, estratégico',
    'tone_mystical': 'Místico, analítico',
    'tone_reflective': 'Reflexivo, íntimo',
    
    // Curriculum Learning Page
    'curriculum_track': 'Pista Curricular',
    'teaching_path_label': 'Camino de Enseñanza',
    'coming_soon': '¡Bienvenido a {title}! Este camino de aprendizaje estará disponible pronto.',
    'curriculum_overview': 'Resumen del Currículo',
    'curriculum_overview_desc': 'Progresa a través de módulos y lecciones estructuradas para dominar esta pista',
    'modules': 'Módulos',
    'lessons': 'Lecciones',
    'completed': 'Completado',
    'module': 'Módulo',
    'lesson_content': 'Contenido de la Lección',
    'practice_exercises': 'Ejercicios de Práctica',
    'mark_complete': 'Marcar como Completado',
    'mark_incomplete': 'Marcar como Incompleto',
    
    // Apologetics Arena
    'apologetics_arena': 'Arena de Apologética',
    'trial_by_truth_subtitle': 'Juicio por la Verdad',
    'circle_of_apologetics': '⚔️ Círculo de Apologética',
    'arena_description': 'Transforma la tensión intelectual en claridad espiritual. Enfrenta un desafiante aleatorio que pondrá a prueba tu apologética a través de la confrontación respetuosa.',
    'random_opponent': 'Oponente Aleatorio',
    'or_click_opponent': 'O haz clic en cualquier oponente arriba para desafiarlo directamente',
    'facing': 'Enfrentando',
    'round': 'Ronda',
    'next_round': 'Siguiente Ronda',
    'debate_complete': 'Debate Completo',
    'debate_complete_desc': 'El juicio ha concluido. Reflexiona sobre lo aprendido.',
    'show_suggested_response': 'Mostrar Respuesta Sugerida',
    'getting_help': 'Obteniendo ayuda...',
    'suggested_apologetic_response': 'Respuesta Apologética Sugerida',
    'use_this_response': 'Usar Esta Respuesta',
    'summoned_to_arena': 'Has invocado a **{name}** a la arena.',
    'stance': 'Postura',
    'challenge': 'Desafío',
    'prepare_yourself': 'Prepárate. El juicio comienza ahora.',
    'round_1_opening': '*Ronda 1: Declaración de Apertura*\nDeclara tu posición claramente. ¿Qué verdad defiendes?',
    'opening_statement': 'Declaración de Apertura',
    'rebuttal': 'Refutación',
    'cross_examination': 'Contrainterrogatorio',
    'closing_statement': 'Declaración Final',
    'the_debate_continues': 'El debate continúa...',
    
    // Arena Personas
    'persona_void': 'El Vacío',
    'persona_void_title': 'Ateo',
    'persona_void_tone': 'Racional, directo',
    'persona_void_challenge': 'Ausencia de significado sagrado',
    'persona_fog': 'La Niebla',
    'persona_fog_title': 'Agnóstico',
    'persona_fog_tone': 'Curioso, vacilante',
    'persona_fog_challenge': 'Miedo a la verdad incognoscible',
    'persona_flame': 'La Llama',
    'persona_flame_title': 'Humanista Secular',
    'persona_flame_tone': 'Ético, confiado',
    'persona_flame_challenge': 'Moralidad sin divinidad',
    'persona_mirror': 'El Espejo',
    'persona_mirror_title': 'Escéptico',
    'persona_mirror_tone': 'Analítico, investigador',
    'persona_mirror_challenge': 'Duda como virtud',
    'persona_river': 'El Río',
    'persona_river_title': 'Panteísta',
    'persona_river_tone': 'Místico, poético',
    'persona_river_challenge': 'Divinidad en todas las cosas',
    'persona_oracle': 'El Oráculo',
    'persona_oracle_title': 'Espiritual Alternativo',
    'persona_oracle_tone': 'Esotérico, simbólico',
    'persona_oracle_challenge': 'Verdad a través de la intuición',
    
    // Arena Error Messages
    'login_required': 'Inicio de sesión requerido',
    'login_required_desc': 'Por favor inicia sesión para comenzar el debate.',
    'login_required_continue': 'Por favor inicia sesión para continuar.',
    'rate_limit_exceeded': 'Límite de tasa excedido',
    'rate_limit_exceeded_desc': 'Por favor intenta de nuevo en un momento.',
    'credits_required': 'Créditos requeridos',
    'credits_required_desc': 'Por favor añade créditos para continuar.',
    'failed_get_response': 'No se pudo obtener respuesta. Por favor intenta de nuevo.',
    
    // Plan of Salvation
    'plan_of_salvation': 'El Plan de Salvación',
    'salvation_intro': '¿Sabías que Dios nos creó para tener una relación con Él?',
    'salvation_p1': 'Nos dio un nombre y un lugar en Él. Nos bendijo con vida eterna en un hermoso jardín y nos confió el dominio sobre toda la creación en la tierra. Fuimos diseñados para caminar con Él, conocerlo íntimamente y vivir en Su presencia para siempre.',
    'salvation_changed': 'Pero todo cambió con la desobediencia de la humanidad.',
    'salvation_p2': 'No fue solo un bocado de fruta o un simple acto de rebelión—fue un intercambio espiritual. Cuando el hombre cedió al engaño de Satanás, no simplemente desobedeció a Dios; lo rechazó y aceptó a Satanás como rey. Al hacerlo, el hombre renunció a la naturaleza de Dios y asumió la naturaleza del enemigo. Satanás, ahora señor sobre el hombre, reclamó la propiedad de todo lo que Dios había dado—incluyendo el alma del hombre.',
    'salvation_purpose': 'Durante miles de años, el propósito de Dios ha permanecido: restaurar esa relación rota.',
    'salvation_p3': 'Sin embargo, algo se interponía en el camino—el pecado. El pecado no solo nos separó de Dios; nos hizo Sus enemigos. No porque Dios se volvió contra nosotros, sino porque nosotros nos volvimos contra Él. El pecado nos esclavizó—no solo en lo que hacemos, sino en quiénes somos. Nos convertimos en transgresores por naturaleza, no solo por acción.',
    'salvation_mercy': 'Pero Dios, en Su misericordia, nos dio a Cristo.',
    'salvation_p4': 'Jesús, el Hijo perfecto y sin pecado de Dios, vino a pagar el precio por los pecados del mundo. Su sacrificio no solo lavó nuestra culpa—saldó nuestra deuda y reconstruyó el puente hacia el Padre. A través de Cristo, cualquiera puede volver a tener una relación con Dios.',
    'salvation_relationship': 'Ser cristiano no se trata de rituales o religión—se trata de relación.',
    'salvation_p5': 'Así como esperamos lealtad, amor y cuidado en nuestras relaciones, Dios ofrece todo eso primero. Él es fiel, amoroso y siempre trabaja para nuestro bien. Y nos invita a responder—no por obligación, sino por amor. Él no exige nuestra devoción; la desea libremente dada.',
    'salvation_done': 'Dios ha hecho todo para reavivar la relación.',
    'salvation_choice': 'Ahora la elección es tuya. ¿Lo recibirás hoy?',
    'prayer_header': 'Oración para Recibir a Cristo',
    'salvation_prayer': '"Señor Jesús, vengo a Ti hoy porque reconozco mi necesidad de Ti. Creo que eres el Hijo de Dios, que moriste por mis pecados y que resucitaste para darme nueva vida. Confieso que he vivido apartado de Ti, y pido Tu perdón. Límpiame. Restáurame. Rindo mi corazón a Ti. Sé mi Salvador, mi Señor y mi Rey. Llé name con Tu Espíritu y enséñame a caminar contigo cada día. Gracias por amarme primero. Hoy, te elijo. Amén."',
    'welcome_family': 'Bienvenido a la Familia',
    'salvation_welcome': 'Si has tomado esta decisión y has orado esta oración, nos regocijamos contigo y te damos la bienvenida a la familia de Cristo—y a nuestra humilde familia Hagion. No estás solo. Has comenzado un viaje de restauración, verdad y amor.',
    'salvation_grow': 'Para ayudarte a crecer, te animamos a ir al ícono de Discernimiento en la aplicación Hagion. En "Iglesias", escribe tu ciudad natal y estado y busca iglesias con sana doctrina. Únete a una de nuestras familias cristianas cerca de ti.',
    'salvation_test': 'En Hagion, te animamos con amor a probar el espíritu—no con sospecha, sino con sabiduría. Proporcionamos herramientas, información y orientación para ayudarte a discernir la visión de cada iglesia y asegurarte de que se alinee con el corazón de Cristo. Este es tu viaje, y nos honra caminar contigo.',
    'accept': 'Aceptar',
    'accepting': 'Registrando...',
    'joined_today': 'se unieron hoy',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'es' || saved === 'en') ? saved : 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
